/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerServiceGUi;

//import roommanager.Options;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import rmi.RoomManager;

public class CustomerService extends javax.swing.JFrame {

    /**
     * Creates new form HotelClient
     */
    public CustomerService() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBook = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jButtonBook1 = new javax.swing.JButton();
        jButtonBook2 = new javax.swing.JButton();
        jButtonBook3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 550, 375));
        setMinimumSize(new java.awt.Dimension(600, 425));
        setSize(new java.awt.Dimension(550, 375));
        getContentPane().setLayout(null);

        jButtonBook.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButtonBook.setText("Report Issue");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook);
        jButtonBook.setBounds(220, 250, 200, 30);

        jLabelTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelTitle.setText(" Customer Service");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(200, 50, 240, 50);

        jButtonBook1.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButtonBook1.setText("Add Service");
        jButtonBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBook1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook1);
        jButtonBook1.setBounds(220, 130, 200, 30);

        jButtonBook2.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButtonBook2.setText("Edit Service");
        jButtonBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBook2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook2);
        jButtonBook2.setBounds(220, 170, 200, 30);

        jButtonBook3.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButtonBook3.setText("Remove Service");
        jButtonBook3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBook3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook3);
        jButtonBook3.setBounds(220, 210, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
       
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBook1ActionPerformed

    private void jButtonBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBook2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBook2ActionPerformed

    private void jButtonBook3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBook3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBook3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerService.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerService().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonBook1;
    private javax.swing.JButton jButtonBook2;
    private javax.swing.JButton jButtonBook3;
    private javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables

}
