/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package CustomerGUi;

import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;


public class StudentFeedBack extends javax.swing.JFrame {

  
    public StudentFeedBack() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        CourseIDField = new javax.swing.JTextField();
        CourseIDlabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BackBtn = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        Evaluation = new javax.swing.JLabel();
        CourseIDlabel1 = new javax.swing.JLabel();
        DateField = new javax.swing.JTextField();
        CourseIDlabel2 = new javax.swing.JLabel();
        TaRateField = new javax.swing.JTextField();
        CommentsField = new javax.swing.JTextField();
        CourseIDlabel4 = new javax.swing.JLabel();

        jLabel2.setPreferredSize(new java.awt.Dimension(120, 120));

        getContentPane().setLayout(null);

        CourseIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CourseIDFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CourseIDField);
        CourseIDField.setBounds(120, 350, 200, 30);

        CourseIDlabel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CourseIDlabel.setText("CustomerID");
        getContentPane().add(CourseIDlabel);
        CourseIDlabel.setBounds(10, 350, 100, 30);

        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 120, 680, 150);

        BackBtn.setText("Back");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        getContentPane().add(BackBtn);
        BackBtn.setBounds(30, 500, 90, 30);

        SubmitBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitBtn.setText("Submit FeedBack");
        getContentPane().add(SubmitBtn);
        SubmitBtn.setBounds(260, 480, 290, 40);

        Evaluation.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Evaluation.setText("FeedBack");
        getContentPane().add(Evaluation);
        Evaluation.setBounds(330, 70, 90, 30);

        CourseIDlabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CourseIDlabel1.setText("Date");
        getContentPane().add(CourseIDlabel1);
        CourseIDlabel1.setBounds(20, 400, 100, 30);

        DateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(DateField);
        DateField.setBounds(120, 400, 200, 30);

        CourseIDlabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CourseIDlabel2.setText("Rate");
        getContentPane().add(CourseIDlabel2);
        CourseIDlabel2.setBounds(380, 340, 100, 30);

        TaRateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TaRateFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TaRateField);
        TaRateField.setBounds(490, 340, 200, 30);

        CommentsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentsFieldActionPerformed(evt);
            }
        });
        getContentPane().add(CommentsField);
        CommentsField.setBounds(490, 400, 200, 30);

        CourseIDlabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CourseIDlabel4.setText("Complain");
        getContentPane().add(CourseIDlabel4);
        CourseIDlabel4.setBounds(360, 400, 110, 30);
    }// </editor-fold>//GEN-END:initComponents

    private void CourseIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CourseIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CourseIDFieldActionPerformed

    private void DateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DateFieldActionPerformed

    private void TaRateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TaRateFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TaRateFieldActionPerformed

    private void CommentsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommentsFieldActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BackBtnActionPerformed

    public JButton getBackBtn() {
        return BackBtn;
    }

    public JTextField getCommentsField() {
        return CommentsField;
    }

 
    public JTextField getDateField() {
        return DateField;
    }

    public JTextField getTaRateField() {
        return TaRateField;
    }

  

    public JTextField getCourseIDField() {
        return CourseIDField;
    }

    public JLabel getCourseIDlabel() {
        return CourseIDlabel;
    }

    public JLabel getEvaluation() {
        return Evaluation;
    }

 

    public JButton getSubmitBtn() {
        return SubmitBtn;
    }



    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    
    
    public static void main(String args[]) {

        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentFeedBack().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField CommentsField;
    private javax.swing.JTextField CourseIDField;
    private javax.swing.JLabel CourseIDlabel;
    private javax.swing.JLabel CourseIDlabel1;
    private javax.swing.JLabel CourseIDlabel2;
    private javax.swing.JLabel CourseIDlabel4;
    private javax.swing.JTextField DateField;
    private javax.swing.JLabel Evaluation;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField TaRateField;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
