/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rminewclient;

//import roommanager.Options;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import rmi.RoomManager;

public class BookRoom extends javax.swing.JFrame {

    /**
     * Creates new form HotelClient
     */
    public BookRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBook = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jComboBoxRoomType = new javax.swing.JComboBox<>();
        jLabelRoomType = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jTextFieldGuestId = new javax.swing.JTextField();
        jLabelGuestId = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 550, 375));
        setMinimumSize(new java.awt.Dimension(600, 425));
        setSize(new java.awt.Dimension(550, 375));
        getContentPane().setLayout(null);

        jButtonBook.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        jButtonBook.setText("Book");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook);
        jButtonBook.setBounds(240, 320, 94, 37);

        jButtonBack.setFont(new java.awt.Font("Trebuchet MS", 0, 16)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(10, 10, 70, 30);

        jComboBoxRoomType.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jComboBoxRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "4" }));
        getContentPane().add(jComboBoxRoomType);
        jComboBoxRoomType.setBounds(330, 250, 60, 27);

        jLabelRoomType.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelRoomType.setText("Room Type");
        getContentPane().add(jLabelRoomType);
        jLabelRoomType.setBounds(190, 250, 130, 29);

        jTextFieldName.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        getContentPane().add(jTextFieldName);
        jTextFieldName.setBounds(240, 190, 193, 32);

        jLabelName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelName.setText("Name");
        getContentPane().add(jLabelName);
        jLabelName.setBounds(150, 190, 70, 29);

        jTextFieldGuestId.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextFieldGuestId.setToolTipText("");
        getContentPane().add(jTextFieldGuestId);
        jTextFieldGuestId.setBounds(290, 140, 127, 31);

        jLabelGuestId.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabelGuestId.setText("Guest ID");
        getContentPane().add(jLabelGuestId);
        jLabelGuestId.setBounds(160, 140, 100, 29);

        jLabelTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        jLabelTitle.setText("Book Room");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(200, 50, 190, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookingbackground.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(550, 375));
        jLabel1.setPreferredSize(new java.awt.Dimension(550, 375));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 600, 410);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        try {
            Registry r = LocateRegistry.getRegistry("127.0.0.1", 1099);
            RoomManager rm = (RoomManager) r.lookup("HelloService");
            //System.out.println();
            String gid = jTextFieldGuestId.getText();
            String name = jTextFieldName.getText();
            String rType = String.valueOf(jComboBoxRoomType.getSelectedItem());
                      
            rm.book(gid, name, rType);
            
            
	} catch (RemoteException | NotBoundException e) {
            e.printStackTrace();
        }
        
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new Options().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRoom().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JComboBox<String> jComboBoxRoomType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelGuestId;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelRoomType;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JTextField jTextFieldGuestId;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

}
