<<<<<<< HEAD
package rminewclient;



import rminewclient.Customer;
import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import rmi.RoomManager;
import rminewclient.BookRoom;



=======
>>>>>>> 7cd38e7a49e3d1d63f7895efe54934e39f2cdb8e
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
<<<<<<< HEAD

public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form Options
=======
package rminewclient;

/**
 *
 * @author DeS
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
>>>>>>> 7cd38e7a49e3d1d63f7895efe54934e39f2cdb8e
     */
    public MainWindow() {
        initComponents();
    }

    /**
<<<<<<< HEAD
     * This method is called from within the constructor to initialise the form.
=======
     * This method is called from within the constructor to initialize the form.
>>>>>>> 7cd38e7a49e3d1d63f7895efe54934e39f2cdb8e
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

<<<<<<< HEAD
        jButtonBook = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButtonAvailable1 = new javax.swing.JButton();
        jButtonBook1 = new javax.swing.JButton();
        jButtonBook2 = new javax.swing.JButton();
        jLabelBackground = new javax.swing.JLabel();
        jButtonAvailable2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 550, 375));
        setMinimumSize(new java.awt.Dimension(585, 415));
        setSize(new java.awt.Dimension(550, 375));
        getContentPane().setLayout(null);

        jButtonBook.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonBook.setText("Book Property");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook);
        jButtonBook.setBounds(160, 220, 220, 30);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setText("Choose The Service");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(40, 40, 480, 60);

        jButtonAvailable1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonAvailable1.setText("Book Car");
        jButtonAvailable1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvailable1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAvailable1);
        jButtonAvailable1.setBounds(160, 140, 220, 30);

        jButtonBook1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonBook1.setText("Book Flight");
        jButtonBook1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBook1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook1);
        jButtonBook1.setBounds(160, 260, 220, 30);

        jButtonBook2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonBook2.setText("Book Hotel");
        jButtonBook2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBook2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook2);
        jButtonBook2.setBounds(160, 180, 220, 30);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/optionsbackground.jpg"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(550, 375));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(550, 375));
        jLabelBackground.setPreferredSize(new java.awt.Dimension(550, 375));
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, 0, 570, 390);

        jButtonAvailable2.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonAvailable2.setText("Book Car");
        jButtonAvailable2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvailable2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAvailable2);
        jButtonAvailable2.setBounds(10, 140, 220, 30);
=======
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
>>>>>>> 7cd38e7a49e3d1d63f7895efe54934e39f2cdb8e

        pack();
    }// </editor-fold>//GEN-END:initComponents

<<<<<<< HEAD
    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        new BookRoom().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonAvailable1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvailable1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAvailable1ActionPerformed

    private void jButtonAvailable2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvailable2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAvailable2ActionPerformed

    private void jButtonBook1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBook1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBook1ActionPerformed

    private void jButtonBook2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBook2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonBook2ActionPerformed

    private void jButtonAvailableActionPerformed(java.awt.event.ActionEvent evt) {                                            
        new BookRoom().setVisible(true);
        this.setVisible(false);
    }                                           


=======
>>>>>>> 7cd38e7a49e3d1d63f7895efe54934e39f2cdb8e
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
<<<<<<< HEAD
        //</editor-fold>
=======
>>>>>>> 7cd38e7a49e3d1d63f7895efe54934e39f2cdb8e

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
<<<<<<< HEAD
    private javax.swing.JButton jButtonAvailable1;
    private javax.swing.JButton jButtonAvailable2;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonBook1;
    private javax.swing.JButton jButtonBook2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackground;
=======
>>>>>>> 7cd38e7a49e3d1d63f7895efe54934e39f2cdb8e
    // End of variables declaration//GEN-END:variables
}
