package rminewclient;



import rminewclient.Customer;
import java.rmi.AccessException;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.logging.Level;
import java.util.logging.Logger;
import rmi.RoomManager;
import rminewclient.BookRoom;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

public class Options extends javax.swing.JFrame {

    /**
     * Creates new form Options
     */
    public Options() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialise the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonAvailable = new javax.swing.JButton();
        jButtonBook = new javax.swing.JButton();
        jButtonGuests = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabelBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 550, 375));
        setMinimumSize(new java.awt.Dimension(585, 415));
        setSize(new java.awt.Dimension(550, 375));
        getContentPane().setLayout(null);

        jButtonAvailable.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonAvailable.setText("Available Rooms");
        jButtonAvailable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvailableActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAvailable);
        jButtonAvailable.setBounds(170, 150, 220, 30);

        jButtonBook.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonBook.setText("Book Room");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook);
        jButtonBook.setBounds(170, 220, 220, 30);

        jButtonGuests.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jButtonGuests.setText("Guests");
        jButtonGuests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuestsActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonGuests);
        jButtonGuests.setBounds(170, 290, 220, 30);

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 48)); // NOI18N
        jLabel1.setText("WELCOME !");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 40, 260, 60);

        jLabelBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/optionsbackground.jpg"))); // NOI18N
        jLabelBackground.setMaximumSize(new java.awt.Dimension(550, 375));
        jLabelBackground.setMinimumSize(new java.awt.Dimension(550, 375));
        jLabelBackground.setPreferredSize(new java.awt.Dimension(550, 375));
        getContentPane().add(jLabelBackground);
        jLabelBackground.setBounds(0, -10, 570, 390);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed
        new BookRoom().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonAvailableActionPerformed(java.awt.event.ActionEvent evt) {                                            
        new BookRoom().setVisible(true);
        this.setVisible(false);
    }                                           


    private void jButtonGuestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuestsActionPerformed
       Customer n;
        try {
            n = new Customer();
            n.setVisible(true);
        } catch (RemoteException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        } catch (NotBoundException ex) {
            Logger.getLogger(Options.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        this.setVisible(false);
    }//GEN-LAST:event_jButtonGuestsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Options.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Options().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAvailable;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JButton jButtonGuests;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBackground;
    // End of variables declaration//GEN-END:variables
}
