/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package BookingGUi;

//import roommanager.Options;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import rmi.RoomManager;
import CustomerGUi.CustomerMenu;

public class BookRoom extends javax.swing.JFrame {

    /**
     * Creates new form HotelClient
     */
    public BookRoom() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @return 
     */
    @SuppressWarnings("unchecked")
        
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonBook = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ErrorLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximizedBounds(new java.awt.Rectangle(0, 0, 550, 375));
        setMinimumSize(new java.awt.Dimension(600, 425));
        setSize(new java.awt.Dimension(550, 375));
        getContentPane().setLayout(null);

        jButtonBook.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jButtonBook.setText("Book");
        jButtonBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBookActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBook);
        jButtonBook.setBounds(460, 340, 94, 37);

        jButtonBack.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jButtonBack.setText("Back");
        jButtonBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonBack);
        jButtonBack.setBounds(10, 10, 70, 30);

        jLabelTitle.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabelTitle.setText("Choose your package");
        getContentPane().add(jLabelTitle);
        jLabelTitle.setBounds(60, 60, 390, 50);

        jTable2.setFont(new java.awt.Font("Times New Roman", 0, 13)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"", ""},
                {"", ""},
                {"", ""},
                {null, null}
            },
            new String [] {
                "Number", "Unit Type"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(60, 120, 452, 100);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 260, 70, 21);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(150, 260, 120, 22);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bookingbackground.jpg"))); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(550, 375));
        jLabel1.setPreferredSize(new java.awt.Dimension(550, 375));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 650, 520);
        getContentPane().add(ErrorLabel);
        ErrorLabel.setBounds(100, 340, 0, 0);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBookActionPerformed

        
    }//GEN-LAST:event_jButtonBookActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        new CustomerMenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButtonBackActionPerformed

    public JLabel getjLabel2() {
        return jLabel2;
    }

    public JTextField getjTextField1() {
        return jTextField1;
    }

    public JButton getjButtonBack() {
        return jButtonBack;
    }

    public JButton getjButtonBook() {
        return jButtonBook;
    }

    public JLabel getjLabel1() {
        return jLabel1;
    }

    public JLabel getjLabelTitle() {
        return jLabelTitle;
    }

    public JScrollPane getjScrollPane2() {
        return jScrollPane2;
    }

    public JTable getjTable2() {
        return jTable2;
    }

    public JLabel getErrorLabel() {
        return ErrorLabel;
    }

    public void setErrorLabel(String ErrorLabel) {
        this.ErrorLabel.setText(ErrorLabel);
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BookRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BookRoom().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorLabel;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonBook;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
